In [ ]:
pwd

'm:\\Data science career\\machine learning\\DataCleaning'

In [1]:
import numpy as np

arr=np.array(
    [
    [3,4,5],
    [5,6,7],
    [8,1,2]
    ]
      )
print(arr)
print(type(arr))
print(arr.shape)


[[3 4 5]
 [5 6 7]
 [8 1 2]]
<class 'numpy.ndarray'>
(3, 3)


In [2]:
arr2=np.zeros(
    (2,3)
    )
print(arr2)
arr3=np.ones(
    (3,3)
    )
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [3]:
arr3=np.full (
              (3,3),
                -1
               )
print(arr3)

[[-1 -1 -1]
 [-1 -1 -1]
 [-1 -1 -1]]


In [4]:
arr4=np.eye(5)
print(arr4)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [5]:
test_arr=np.array([
                    [3,  5 ,  7,12],
                    [9 , 3 , 12,10] ,
                    [5 , 1 ,  8,23],
                    [12 ,3,   5, 21]
                  ])
print(test_arr[ 1:3,1:3  ])
print(test_arr.T)

[[ 3 12]
 [ 1  8]]
[[ 3  9  5 12]
 [ 5  3  1  3]
 [ 7 12  8  5]
 [12 10 23 21]]


In [6]:
ages = np.array([12, 25, 17, 19, 30, 15, 21,17])  
mask=ages>18
#print(ages[mask])

ages2 = np.array([12, 25, 17, 19, 30, 15, 21,17]) 
print(ages2.reshape(1,8))

[[12 25 17 19 30 15 21 17]]


In [7]:
import pandas as pd

In [8]:
pwd

'm:\\Data science career\\machine learning\\DataCleaning'

In [9]:
data1=pd.read_csv("datasets/data-example2.csv")

In [10]:
print(data1.head())

    x1  x2   x3  x4    x5    x6  x7
0  1.0   2  5.0   0   4.0   NaN  10
1  1.0  15  NaN   1  16.0   2.0   ?
2  NaN   3  1.0   2   3.2   4.0   2
3  5.0   4  6.0   8   1.0   NaN   ?
4  7.0   3  NaN   6   5.0  15.0   3


In [11]:
data2=data1.drop(columns=['name','tall'])
print(data2)

KeyError: "['name', 'tall'] not found in axis"